### ISSUE TITLE
How to install? How to use?

### ISSUE THREAD

**Issue by sweded** [mattrajca/Safari-Extensions#4]
Hi,

It would be great to include some installation instructions. Things to mention are that you need a Safari Dev cert and the extensions are installed using Extension Builder. While it's easy enough to figure out, it's not very obvious.

After installing the Subtle Patterns extension, it's available but I'm not sure how to use it. I can select various patterns but I can't figure out how to apply them. 

Thanks,
Gernot

**Comment by mattrajca** [comment]
If you download the release build of the extension you don't need to use the Developer menu / Extension Builder: https://github.com/mattrajca/Safari-Extensions/downloads  The extension will appear in Safari -> Preferences -> Extensions.

Clicking a pattern will apply it as a tiled background image to a page's `body` element. If you don't see it, the page was likely designed such that other elements are obstructing the background.

**Comment by sweded** [comment]
Thanks, it looks like I just grabbed the zip on the code page. I think I was hoping I could apply the background on various elements.
